# Generated by Django 5.1.3 on 2026-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='strength',
        ),
        migrations.AddField(
            model_name='player',
            name='mu',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='sigma',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
    ]
