# Generated by Django 5.1.3 on 2026-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_player_strength_player_mu_player_sigma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sigma',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
    ]
