# Generated by Django 5.1.3 on 2026-06-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_court_alter_match_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.match'),
        ),
    ]
