# Generated by Django 5.1.3 on 2026-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_sigma'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersession',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playersession',
            name='games_skipped',
            field=models.IntegerField(default=0),
        ),
    ]
