# Generated by Django 5.1.3 on 2026-06-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playersession_games_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5)),
                ('player_ids', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
    ]
