# Generated by Django 5.1.3 on 2026-06-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_upcomingmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_player1', to='core.playersession')),
                ('player2_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_player2', to='core.playersession')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='core.session')),
            ],
        ),
    ]
