# Generated by Django 5.1.3 on 2026-06-13 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_match_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
