# Generated by Django 5.1.3 on 2026-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_match_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played_weight', models.PositiveIntegerField(default=25, help_text='Playtime fairness')),
                ('fairness_weight', models.PositiveIntegerField(default=10, help_text='Overall match skill fairness (win differential)')),
                ('played_with_weight', models.PositiveIntegerField(default=5, help_text='Teammate repeat penalty')),
                ('played_against_weight', models.PositiveIntegerField(default=3, help_text='Opponent repeat penalty')),
                ('gender_weight', models.PositiveIntegerField(default=2, help_text='Gender balance')),
                ('skill_difference_weight', models.PositiveIntegerField(default=3, help_text='Intra-team skill gap penalty')),
                ('skill_rel_gap_threshold_1', models.FloatField(default=0.2, help_text='Excellent threshold (relative gap)')),
                ('skill_rel_gap_threshold_2', models.FloatField(default=0.35, help_text='Acceptable threshold')),
                ('skill_rel_gap_threshold_3', models.FloatField(default=0.5, help_text='Heavy penalty threshold')),
            ],
            options={
                'verbose_name': 'Matchmaking Configuration',
                'verbose_name_plural': 'Matchmaking Configuration',
            },
        ),
    ]
