# Generated by Django 5.1.3 on 2026-07-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_matchmakingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchmakingconfig',
            name='skill_rel_gap_threshold_1',
        ),
        migrations.RemoveField(
            model_name='matchmakingconfig',
            name='skill_rel_gap_threshold_2',
        ),
        migrations.RemoveField(
            model_name='matchmakingconfig',
            name='skill_rel_gap_threshold_3',
        ),
        migrations.AlterField(
            model_name='player',
            name='sigma',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
        ),
        migrations.CreateModel(
            name='GenderPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN')], max_length=10)),
                ('player1_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_pair_as_player1', to='core.playersession')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_pairs', to='core.session')),
            ],
        ),
    ]
