# Generated by Django 5.1.3 on 2026-07-11 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clubconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
