# Generated by Django 5.1.3 on 2026-07-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderpair',
            name='gender',
            field=models.CharField(choices=[('M', 'MEN'), ('F', 'WOMEN')], max_length=10),
        ),
    ]
