# Generated by Django 5.1.3 on 2026-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_genderpair_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmakingconfig',
            name='played_against_weight',
            field=models.PositiveIntegerField(default=4, help_text='Opponent repeat penalty'),
        ),
        migrations.AlterField(
            model_name='matchmakingconfig',
            name='played_with_weight',
            field=models.PositiveIntegerField(default=7, help_text='Teammate repeat penalty'),
        ),
    ]
