# Generated by Django 5.1.3 on 2026-07-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_matchmakingconfig_played_against_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
