# Generated by Django 5.1.3 on 2026-07-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_match_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingmatch',
            name='queue_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
