# Generated by Django 5.1.3 on 2026-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_upcomingmatch_queue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersession',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
